// lib/institutions-in.ts
export const INDIAN_INSTITUTIONS = [
  "Indian Institute of Technology Madras (IIT Madras)",
  "Indian Institute of Technology Delhi (IIT Delhi)",
  "Indian Institute of Technology Bombay (IIT Bombay)",
  "Indian Institute of Technology Kanpur (IIT Kanpur)",
  "Indian Institute of Technology Kharagpur (IIT Kharagpur)",
  "Indian Institute of Technology Roorkee (IIT Roorkee)",
  "Indian Institute of Technology Guwahati (IIT Guwahati)",
  "Indian Institute of Technology Hyderabad (IIT Hyderabad)",
  "Indian Institute of Technology Indore (IIT Indore)",
  "Indian Institute of Technology BHU Varanasi (IIT BHU)",
  "Indian Institute of Technology Tirupati (IIT Tirupati)",
  "Indian Institute of Technology Palakkad (IIT Palakkad)",
  "Indian Institute of Technology Patna (IIT Patna)",
  "Indian Institute of Technology Ropar (IIT Ropar)",
  "Indian Institute of Technology Mandi (IIT Mandi)",
  "Indian Institute of Technology Jodhpur (IIT Jodhpur)",
  "Indian Institute of Technology Gandhinagar (IIT Gandhinagar)",
  "Indian Institute of Technology Bhubaneswar (IIT Bhubaneswar)",

  "National Institute of Technology Tiruchirappalli (NIT Trichy)",
  "National Institute of Technology Karnataka, Surathkal (NITK)",
  "National Institute of Technology Rourkela (NIT Rourkela)",
  "National Institute of Technology Warangal (NIT Warangal)",
  "National Institute of Technology Calicut (NIT Calicut)",
  "National Institute of Technology Durgapur (NIT Durgapur)",
  "National Institute of Technology Silchar (NIT Silchar)",
  "National Institute of Technology Jaipur (MNIT Jaipur)",
  "National Institute of Technology Nagpur (VNIT Nagpur)",
  "National Institute of Technology Kurukshetra (NIT Kurukshetra)",
  "National Institute of Technology Srinagar (NIT Srinagar)",
  "National Institute of Technology Surat (SVNIT Surat)",
  "National Institute of Technology Patna (NIT Patna)",
  "National Institute of Technology Raipur (NIT Raipur)",
  "National Institute of Technology Jamshedpur (NIT Jamshedpur)",
  "National Institute of Technology Hamirpur (NIT Hamirpur)",
  "National Institute of Technology Puducherry (NIT Puducherry)",

  "Indian Institute of Science (IISc Bengaluru)",
  "Anna University, Chennai",
  "Jadavpur University, Kolkata",
  "University of Madras, Chennai",
  "Bharathiar University, Coimbatore",
  "Bharathidasan University, Tiruchirappalli",
  "Alagappa University, Karaikudi",
  "Madurai Kamaraj University, Madurai",

  "Vellore Institute of Technology (VIT), Vellore",
  "SRM Institute of Science and Technology, Chennai",
  "SASTRA Deemed University, Thanjavur",
  "Amrita Vishwa Vidyapeetham, Coimbatore",
  "PSG College of Technology, Coimbatore",
  "SSN College of Engineering, Chennai",
  "Thiagarajar College of Engineering (TCE), Madurai",
  "Kumaraguru College of Technology, Coimbatore",
  "Coimbatore Institute of Technology (CIT), Coimbatore",
  "Government College of Technology (GCT), Coimbatore",
  "Government College of Engineering, Tirunelveli",
  "Government College of Engineering, Salem",
  "Government College of Engineering, Thanjavur",

  "CEPT University, Ahmedabad",
  "School of Planning and Architecture, Delhi (SPA Delhi)",
  "School of Planning and Architecture, Bhopal (SPA Bhopal)",
  "School of Planning and Architecture, Vijayawada (SPA Vijayawada)",
  "Jamia Millia Islamia, New Delhi",
  "Delhi Technological University (DTU), New Delhi",
  "Netaji Subhas University of Technology (NSUT), New Delhi",
  "Birla Institute of Technology and Science (BITS Pilani)",
  "Manipal Academy of Higher Education (MAHE), Manipal",
  "Savitribai Phule Pune University (SPPU), Pune",
  "University of Mumbai, Mumbai",
  "University of Delhi, New Delhi",
  "Banaras Hindu University (BHU), Varanasi",
  "Aligarh Muslim University (AMU), Aligarh",
  "Panjab University, Chandigarh",
  "Osmania University, Hyderabad",
  "Andhra University, Visakhapatnam",
  "Cochin University of Science and Technology (CUSAT), Kochi",
  "University of Kerala, Thiruvananthapuram",
  "Calicut University, Malappuram",
];